### ISSUE TITLE
li not inside ul

### ISSUE THREAD

**Issue by kolaczyn** [pact64/4#1]
You should always have \<li> inside \<ul> and only \<li> should be a child of \<ul>.
Also, you should put actual links to the boards by putting \<a> tag inside of \<li> tags.
That means that e.g.:
```
<div class="boards-list">
  <li class="board-category">Interests</li>
  <li>Comics & Cartoons</li>
  <li>Technology</li>
</div>
```
Should be changed to:
```
<ul class="boards-list">
  <li class="board-category">Interests</li>
  <li><a href="https://boards.4channel.org/co/">Comics & Cartoons</a></li>
  <li><a href="https://boards.4channel.org/g/">Technology</a></li>
</ul>
```
That change will most likely change the color of the boards names, so you should also update your CSS.

I made [this project](https://github.com/kolaczyn/4chan) when I was starting to learn HTML and CSS, so that's why I've made so many mistakes. I've learned a ton in 6 months, so if you want any help with learning about the front end, feel free to reach out to me

**Comment by pact64** [comment]
ah, thanks. I'm very new to most of this stuff.
